serviceAccounts:
  create: true
  name: ""

strategy: blue

canary:
  enabled: false
  name: canary
  
containers:
  port: 8000

replicaCount: 1

service:
  type: NodePort
  port: 80

environmentVariables:
  NGINX_PORT: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

container_limit_range:
  enabled: true
  requests:
    memory: "512Mi"
    cpu: "1000m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

tolerations:
- key: "nodegroup"
  operator: "Equal"
  value: "common"
  effect: "NoSchedule"

nodeSelector: {}
