{{- if .Values.secretEnvs.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-auth
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnvs }}
  {{$key}}: !!stringEnv {{ $value }}
{{- end }}
{{- end -}}