apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: e6data
    component: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: http
  selector:
    app: e6data
    component: {{ template "name" . }}
---
{{ if eq .Values.strategy "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-preview
  labels:
    app: e6data
    component: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: http
  selector:
    app: e6data
    component: {{ template "name" . }}
{{ end }}